version: '3.8'

services:
  tmfs-scanner:
    build: .
    container_name: tmfs-scanner
    privileged: true  # Required for NFS mounting
    environment:
      - ENDPOINT=192.168.200.50:50051
      - TLS=false
      - PML=false
      - FEEDBACK=false
      - VERBOSE=false
      - ACTIVE_CONTENT=false
      - TAGS=
      - DIGEST=true
      - TM_AM_SCAN_TIMEOUT_SECS=300
      - TM_AM_DISABLE_CERT_VERIFY=0
      - NFS_SERVER=192.168.200.10
      - NFS_SHARE=/mnt/nfs_share
      - ACTION=quarantine
      - SCAN_INTERVAL=30
      - QUARANTINE_DIR=quarantine
    volumes:
      # Mount NFS shares here
      - nfs-share:/mnt/nfs:shared
      # Mount local files for scanning
      - ./files:/app/files:ro
    networks:
      - tmfs-network
    command: ["monitor"]  # Start real-time monitoring

  tmfs-scanner-delete:
    build: .
    container_name: tmfs-scanner-delete
    privileged: true  # Required for NFS mounting
    environment:
      - ENDPOINT=192.168.200.50:50051
      - TLS=false
      - PML=false
      - FEEDBACK=false
      - VERBOSE=false
      - ACTIVE_CONTENT=false
      - TAGS=
      - DIGEST=true
      - TM_AM_SCAN_TIMEOUT_SECS=300
      - TM_AM_DISABLE_CERT_VERIFY=0
      - NFS_SERVER=192.168.200.10
      - NFS_SHARE=/mnt/nfs_share
      - ACTION=delete
      - SCAN_INTERVAL=30
    volumes:
      # Mount NFS shares here
      - nfs-share:/mnt/nfs:shared
      # Mount local files for scanning
      - ./files:/app/files:ro
    networks:
      - tmfs-network
    command: ["monitor"]  # Start real-time monitoring with delete action

  tmfs-scanner-report:
    build: .
    container_name: tmfs-scanner-report
    privileged: true  # Required for NFS mounting
    environment:
      - ENDPOINT=192.168.200.50:50051
      - TLS=false
      - PML=false
      - FEEDBACK=false
      - VERBOSE=false
      - ACTIVE_CONTENT=false
      - TAGS=
      - DIGEST=true
      - TM_AM_SCAN_TIMEOUT_SECS=300
      - TM_AM_DISABLE_CERT_VERIFY=0
      - NFS_SERVER=192.168.200.10
      - NFS_SHARE=/mnt/nfs_share
      - ACTION=report_only
      - SCAN_INTERVAL=30
    volumes:
      # Mount NFS shares here
      - nfs-share:/mnt/nfs:shared
      # Mount local files for scanning
      - ./files:/app/files:ro
    networks:
      - tmfs-network
    command: ["monitor"]  # Start real-time monitoring with report only

  tmfs-scan:
    build: .
    container_name: tmfs-scan
    environment:
      - ENDPOINT=192.168.200.50:50051
      - TLS=false
      - PML=false
      - FEEDBACK=false
      - VERBOSE=false
      - ACTIVE_CONTENT=false
      - TAGS=
      - DIGEST=true
      - TM_AM_SCAN_TIMEOUT_SECS=300
      - TM_AM_DISABLE_CERT_VERIFY=0
    volumes:
      # Mount files to scan
      - ./files:/app/files:ro
    networks:
      - tmfs-network
    command: ["scan", "file:/app/files/eicar.com.txt"]
    depends_on:
      - tmfs-scanner

volumes:
  nfs-share:
    driver: local

networks:
  tmfs-network:
    driver: bridge 