version: '3.8'

services:
  tmfs-cli-scanner:
    build:
      context: .
      dockerfile: Dockerfile.cli
    image: tmfs-cli-scanner
    container_name: tmfs-cli-scanner
    privileged: true  # Required for NFS mounting
    environment:
      # Required: Trend Vision One API Key
      - TM_API_KEY=${TM_API_KEY}
      
      # Optional: Vision One Configuration
      - TM_REGION=${TM_REGION:-us-east-1}
      - TM_ENDPOINT=${TM_ENDPOINT}
      - TM_TLS=${TM_TLS:-true}
      - TM_TIMEOUT=${TM_TIMEOUT:-300}
      
      # NFS Configuration
      - NFS_SERVER=${NFS_SERVER:-192.168.200.10}
      - NFS_SHARE=${NFS_SHARE:-/mnt/nfs_share}
      
      # Monitoring Configuration
      - ACTION=${ACTION:-quarantine}
      - SCAN_INTERVAL=${SCAN_INTERVAL:-30}
      - QUARANTINE_DIR=${QUARANTINE_DIR:-quarantine}
    
    volumes:
      # NFS share volume (shared with host)
      - nfs-share:/mnt/nfs:shared
      
      # Optional: Mount local files for scanning
      - ./files:/app/files:ro
    
    networks:
      - tmfs-network
    
    # Health check
    healthcheck:
      test: ["CMD", "/app/tmcli", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped

  # Service for single scans
  tmfs-cli-scan:
    build:
      context: .
      dockerfile: Dockerfile.cli
    image: tmfs-cli-scanner
    container_name: tmfs-cli-scan
    environment:
      - TM_API_KEY=${TM_API_KEY}
      - TM_REGION=${TM_REGION:-us-east-1}
      - TM_ENDPOINT=${TM_ENDPOINT}
      - TM_TLS=${TM_TLS:-true}
      - TM_TIMEOUT=${TM_TIMEOUT:-300}
    
    volumes:
      # Mount files to scan
      - ./files:/app/files:ro
    
    networks:
      - tmfs-network
    
    profiles:
      - scan  # Only start when explicitly requested

volumes:
  nfs-share:
    driver: local

networks:
  tmfs-network:
    driver: bridge 